services:
  backend-app:
    container_name: backend-app
    image: backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - main
    stdin_open: true
    tty: true
    env_file:
      - ./.env.example
    depends_on:
      - db

  db:
    container_name: postgres_secret_guest
    image: postgres:16
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - main
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: secret-guest
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - secret-guest-pgdata:/var/lib/postgresql/data
      - ./backend/migrations/sql:/docker-entrypoint-initdb.d

  minio:
    container_name: minio_secret_guest
    image: quay.io/minio/minio:latest
    command: [ "server", "--console-address", ":9090", "/mnt/data" ]
    environment:
      MINIO_ROOT_USER: adminuser
      MINIO_ROOT_PASSWORD: admin1234
      MINIO_DEFAULT_BUCKETS: secret-guest-images
      MINIO_USE_SSL: false
    env_file:
      - ./.env.example
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "9090:9090"
    networks:
      - main
    volumes:
      - 'minio-data:/data'

networks:
  main:

volumes:
  secret-guest-pgdata: { }
  minio-data: {}
