/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export interface DocsHotelResponse {
  id?: string;
  location_id?: string;
  location_name?: string;
  name?: string;
}
