/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */
import type { DocsOfferResponse } from './docsOfferResponse';

export interface DocsGetOffersResponse {
  offers?: DocsOfferResponse[];
  pages_count?: number;
}
