/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export interface DocsUpdateOfferRequest {
  check_in_at?: string;
  check_out_at?: string;
  expiration_at?: string;
  hotel_id?: string;
  room_id?: string;
  task?: string;
}
