/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export interface DocsUserResponse {
  email?: string;
  is_admin?: boolean;
  ostrovok_login?: string;
}
