/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export interface DocsApplicationResponse {
  expiration_at?: string;
  hotel_name?: string;
  id?: string;
  offer_id?: string;
  status?: string;
  user_id?: string;
}
