/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export interface DocsAuthResponse {
  access_token?: string;
  access_ttl?: number;
  refresh_token?: string;
  refresh_ttl?: number;
}
