/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export interface DocsOfferResponse {
  check_in_at?: string;
  check_out_at?: string;
  expiration_at?: string;
  hotel_id?: string;
  hotel_name?: string;
  id?: string;
  participants_count?: number;
  participants_limit?: number;
  room_id?: string;
  room_name?: string;
  task?: string;
}
