/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */
import type { DocsHotelResponse } from './docsHotelResponse';

export interface DocsGetHotelsResponse {
  hotels?: DocsHotelResponse[];
}
