/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export type GetApplicationSearchParams = {
/**
 * Id of required city
 */
cityId?: string;
/**
 * Id of required hotel
 */
hotelId?: string;
/**
 * Id of required room
 */
roomId?: string;
/**
 * status of app
 */
status?: string;
/**
 * Number of page
 */
pageNum: number;
/**
 * Size of page
 */
pageSize: number;
};
