/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export type GetReportSearchParams = {
/**
 * cityId if report
 */
cityId?: string;
/**
 * hotelId of report
 */
hotelId?: string;
/**
 * Status of report
 */
status?: string;
/**
 * Number of page
 */
pageNum: number;
/**
 * Size of page
 */
pageSize: number;
};
