/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export type GetReportParams = {
/**
 * Number of page
 */
pageNum: number;
/**
 * Size of page
 */
pageSize: number;
};
