/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export * from './docsApplicationResponse';
export * from './docsAuthResponse';
export * from './docsConfirmReport';
export * from './docsCreateApplicationRequest';
export * from './docsCreateApplicationResponse';
export * from './docsCreateHotelRequest';
export * from './docsCreateHotelResponse';
export * from './docsCreateLocationRequest';
export * from './docsCreateLocationResponse';
export * from './docsCreateOfferRequest';
export * from './docsCreateOfferResponse';
export * from './docsCreateRoomRequest';
export * from './docsCreateRoomResponse';
export * from './docsGetApplicationsResponse';
export * from './docsGetByApplicationIdResponse';
export * from './docsGetHotelsResponse';
export * from './docsGetLocationsResponse';
export * from './docsGetOffersResponse';
export * from './docsGetReportsResponse';
export * from './docsGetRoomsResponse';
export * from './docsGetUserAppLimitInfoResponse';
export * from './docsHotelResponse';
export * from './docsLocationResponse';
export * from './docsLogInRequest';
export * from './docsOfferResponse';
export * from './docsRefreshRequest';
export * from './docsReportImageResponse';
export * from './docsReportResponse';
export * from './docsRoomResponse';
export * from './docsSignUpRequest';
export * from './docsUpdateOfferRequest';
export * from './docsUserResponse';
export * from './getApplicationParams';
export * from './getApplicationSearchParams';
export * from './getOfferParams';
export * from './getOfferSearchParams';
export * from './getReportMyParams';
export * from './getReportParams';
export * from './getReportSearchParams';
export * from './patchReportIdBody';