/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Secret Guest API
 * API for "Secret Guest" app
 * OpenAPI spec version: 1.0
 */

export type PatchReportIdBody = {
  /** Report text */
  text: string;
  /** Report images */
  images: Blob;
};
